### ISSUE TITLE
Integration in rstan?

### ISSUE THREAD

**Issue by tmalsburg** [nathanvan/rstanmulticore#1]
Thank you for `pstan`!  I think it's useful for all users of rstan.  Wouldn't it make sense to integrate it into rstan.

BTW, the package requires R 3.1.1 but it seems to work fine with R 3.0.2 which is provided with Ubuntu 14.04 LTS.

**Comment by nathanvan** [comment]
I believe that the rstan developers will eventually support a native parallel framework eventually, but it isn't clear to me what route they will choose to do so. The package is, essentially, intended to be a temporary fix. 

I'll downgrade the required version to R 3.1.1.

**Comment by nathanvan** [comment]
I set the required version of R to 2.14.0, which is the minimum required version for rstan.
